# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#header"
  weight = 10

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 20

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Our Team"
  url = "#people"
  weight = 50

[[main]]
  name = "Job Opportunities"
  url = "#opportunities"
  weight = 55

[[main]]
  name = "Teaching"
  identifier = "teaching"
  # pageRef = "#teaching"
  weight = 57

[[main]]
  name = "Biomedical Informatics"
  parent = "teaching"
  url = "/teaching/biomedical-informatics/"

[[main]]
  name = "Fokuswoche Digitalisierung"
  parent = "teaching"
  url = "/teaching/Fokuswoche-Digitalisierung/"

[[main]]
  name = "Introduction to Digital Health"
  parent = "teaching"
  url = "/teaching/Introduction-to-Digital-Health/"

[[main]]
  name = "Machine Learning – An Interdisciplinary Introduction"
  parent = "teaching"
  url = "/teaching/Machine-Learning-–-An-Interdisciplinary-Introduction/"


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
